steps:
  - label: ":hammer: Example Script"
    command: echo "Hello Buildkite !!"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"
  
  - label: ":pipeline Compile:"
    command: "mvn compile && echo Compiled Successfully !!"
  
  - label: ":pipeline: Build"
    command: "mvn clean && mvn package && Built Successully !!"