steps:
  - label: ":hammer: Example Script"
    command: echo "Hello Buildkite !!"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"
  
  - label: ":pipeline: Set Vault Token"
    command: echo "$BUILDKITE_VAULT"
    key: trigger-environment
  
  - label: ":pipeline: Compile"
    command: "mvn compile"
  
  - label: ":pipeline: Build"
    command: "mvn clean && mvn package"